// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func joinLobbyConfirmation(lobby string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h2 class=\"text-white text-3xl mb-2\">Confirm</h2><ul class=\"rounded-lg border-white border-4 border-solid list-disc list-inside p-5\"><li class=\"text-white mb-4 list-none\">You are about to join a match with: lksdjflskfdjslfjsljfsjkfksjfjk</li><li class=\"text-white mb-4 list-none\">Please enter your name:</li><input type=\"text\" id=\"playerName\" class=\"rounded-lg w-full p-2.5\" required maxlength=\"25\"></ul><div class=\"flex items-center justify-between\"><button class=\"bg-green-500 border rounded-lg px-6 py-4 shadow-md text-white text-3xl mt-8 hover:bg-green-600\" hx-get=\"/\" hx-push-url=\"true\" hx-trigger=\"click\" hx-target=\"body\">Confirm\r</button> <button class=\"bg-red-500 border rounded-lg px-6 py-4 shadow-md text-white text-3xl mt-8 hover:bg-red-600\" hx-get=\"/lobby\" hx-push-url=\"true\" hx-trigger=\"click\" hx-target=\"body\">Back\r</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
